apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stable

resources:
- ../../base
- ./ingress.yml

images:
- name: ghcr.io/weit-1st/odya
  newTag: stable

patchesStrategicMerge:
- patch.yml
- deployment.yml
