apiVersion: apps/v1
kind: Deployment
metadata:
  name: odya-api
spec:
  selector:
    matchLabels:
      app: odya-api
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: odya-api
    spec:
      containers:
        - image: ghcr.io/weit-1st/odya:latest
          imagePullPolicy: Always
          name: odya-api
          volumeMounts:
          - name: oracle-config
            mountPath: /oracle
            readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
          ports:
            - containerPort: 8080
          env:
            - name: APP_PHASE
              value: sandbox
            - name: APP_NAME
              value: odya-api
            - name: OBJECT_STORAGE_CONFIG_FILE_PATH
              valueFrom:
                secretKeyRef:
                  name: odya-secret
                  key: object_strage_config
            - name: TNS_ADMIN
              valueFrom:
                secretKeyRef:
                  name: odya-secret
                  key: tnsAdmin
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: odya-secret
                  key: awsSecretKey
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: odya-secret
                  key: awsAccessKey
            - name: JAVA_TOOL_OPTIONS
              value: >
                -XX:InitialRAMPercentage=50
                -XX:MaxRAMPercentage=80
                -XX:MinRAMPercentage=80
          readinessProbe:
            httpGet:
              port: 8080
              path: /ready
            initialDelaySeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /health
            initialDelaySeconds: 130
            timeoutSeconds: 10
            failureThreshold: 10
      volumes:
        - name: share-vol
          emptyDir: {}
        - name: oracle-config
          hostPath:
            path: /oracle
            type: Directory
      imagePullSecrets:
        - name: ghcr-login-secret
