apiVersion: v1
kind: Service
metadata:
  name: odya-api-svc
  annotations:
    prometheus/scrape: "true"
    prometheus/scheme: "http"
    prometheus/port: "8888"
    prometheus/path: "/actuator/prometheus"
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: odya-api
