#Dockerfile
FROM jenkins/jenkins:jdk17

USER root

RUN apt-get update && apt-get upgrade -y

RUN curl -fsSL https://get.docker.com/ | sh

RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/arm64/kubectl"

RUN curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash

RUN mv kustomize /usr/local/bin/

RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

RUN usermod -aG docker jenkins

USER jenkins
