apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: infra
spec:
  ports:
    - nodePort: 30000
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
  type: NodePort
