apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: infra
data:
  redis-config: |
    protected-mode yes
    bind 0.0.0.0
    requirepass password
    maxmemory 4gb
    maxmemory-policy allkeys-lru
    dir /redis-master-data
    appendonly no
    save 300 1
